name: build

on:
  push:
    paths-ignore:
      - 'public/build/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - run: npm install
      - run: npm run build

      - run: |
          git config --global user.email "statuspage-autobuild@dankmemer.gg"
          git config --global user.name "Statuspage Autobuild"
      
      - run: |
          git add -f public/build/*
          git commit -m "[build] $(git rev-parse --short HEAD)" || exit 0
          git push origin master
